### ISSUE TITLE
Very nice T-shirt configurator but ask AI does not work

### ISSUE THREAD

**Issue by Arakistech** [kt946/ai-threejs-products-app-yt-jsm#1]

**Comment by kt946** [comment]
Apologies, but the "Ask AI" feature is currently not functioning due to my API key exceeding the usage limits as of April 2023. As a result, I've deactivated the key and do not plan to reactivate it. Although the AI feature requires an active key, the code still works and users can still use uploaded images to decorate their shirts. Thanks for your understanding.
